### ISSUE TITLE
Make the mouse a really heavy node!

### ISSUE THREAD

**Issue by dbkaplun** [pakastin/nodegarden#1]

**Comment by pakastin** [comment]
Great idea, will make! ;)

**Comment by pakastin** [comment]
Actually I made the mouse a generator..but I will iterate your idea as well.

**Comment by pakastin** [comment]
I will make this so that when you keep your mouse pressed down, it becomes a huge node. Now it works temporarily with keeping shift key pressed – have fun! ;)

**Comment by dbkaplun** [comment]
Well done!

**Comment by pakastin** [comment]
Actually now it's with mousedown! :D
