### ISSUE TITLE
Mouse position broken on retina screen

### ISSUE THREAD

**Issue by jamesyc** [pakastin/nodegarden#10]
OSX 10.11.1 Google Chrome. Similar problem on Firefox for Mac as well. 

The x,y coordinate of where the mouse clicks is exactly halfway from the top left corner of the page, compared to the mouse's actual position. Everything on the canvas is rendered at half position.

**Comment by pakastin** [comment]
Thanks! #9 fixes this

**Comment by pakastin** [comment]
#9 fixed this.
