### ISSUE TITLE
browser version

### ISSUE THREAD

**Issue by skynet** [pakastin/nodegarden#11]
how do we run this statically with a regular server (not nodejs)

**Comment by pakastin** [comment]
Hi! Everything you'll need are here:
https://github.com/pakastin/nodegarden/tree/master/public

index.html, css/main.css and js/main.js

You could for example just embed the index.html with an iframe..

**Comment by pakastin** [comment]
Node.js is there for just watching the source files and bundling the UMD package..

**Comment by pakastin** [comment]
Another way is to include the JS in your own HTML (just before closing </body>)
You'll need two DOM elements: `#container` and `.moon`

Or you can modify the requested element names here:
https://github.com/pakastin/nodegarden/blob/master/public/js/main-dev.js#L252

**Comment by skynet** [comment]
Thanks!
