### ISSUE TITLE
'Position: fixed' mouse event listener not fixed. Scrolling causes mouse tracking to fail.

### ISSUE THREAD

**Issue by Chillstice** [pakastin/nodegarden#12]
I'm interested in using a modified version of NodeGarden as an interesting background element on a personal website I'm currently developing. At the moment I'm having issues regarding webpage scaling. I currently have two paths: dynamically stretch the container div's size to be the same size as the entire document (including scrolling) or make the div position:fixed so that it can remain the size of the viewport, but move with the screen. With the latter, mouse click events can be de-synced by scrolling the page. Mouse click events act as if the container div is still positon:absolute at the top of the page. Even scrolling a little bit and clicking allows you to better visualize this effect. I would publish a wip version of my site, but this effect already exists on another website which may be a better example: https://level1techs.com/video

I know it's been a few years, but I would like some advice regarding whether or not I should pursue dynamically stretching the canvas down the entire document using position:absolute or just using position:fixed. I would like to see this scrolling issue solved for fixed positioning.

**Comment by pakastin** [comment]
I think you could just substract scrollTop and scrollLeft from e.pageX and e.pageY here: https://github.com/pakastin/nodegarden/blob/master/scripts/index.js

I get back to this after new year.. Happy 2018!

**Comment by Chillstice** [comment]
I haven't been able to get that solution to work. I imagine it's an easy fix, but I can't figure it out. Here's my example: https://chillstice.com

**Comment by pakastin** [comment]
Should work now after a big update..?

**Comment by pakastin** [comment]
Fixed it with `window.scrollX` and `window.scrollY`:
https://github.com/pakastin/nodegarden/blob/cd91eeaa1b4592837147fc45560ed826fede16a7/scripts/index.js#L22-L38

**Comment by Chillstice** [comment]
That solved it
